---
# Puppet Classes to load and execute
classes:
  - oracle::12c::client
  - swap_file
  - etc_services::hiera
  - documentum

# Repository Configuration

documentum::contentserver::repository::ensure:                'file'
documentum::contentserver::repository::documentum:            '/u01/app/documentum'
documentum::contentserver::repository::version:               '7.3'
documentum::contentserver::repository::installer:             '/u01/app/documentum/product/7.3/install'
documentum::contentserver::repository::docbroker_port:        '1489'
documentum::contentserver::repository::docbroker_name:        'Docbroker'
documentum::contentserver::repository::docbroker_host:        'dctm.local'
documentum::contentserver::repository::documentum_data:       '/vagrant/repositorydata'
documentum::contentserver::repository::repository_name:       'FCMS'
documentum::contentserver::repository::repository_id:         '10170110'
documentum::contentserver::repository::repository_service:    'dm_fcms'
documentum::contentserver::repository::repository_desc:       'auto repo build'
documentum::contentserver::repository::bof_registry_password: '1234qwer'
documentum::contentserver::repository::db_user:               'fcmsdb'
documentum::contentserver::repository::db_password:           'fcmsdb'
documentum::contentserver::repository::db_connection:         'orcl'
documentum::contentserver::repository::db_tablespace:         'fcms'
documentum::contentserver::repository::service_name:          'jms'


# UNIX groups
group:
  dba:
    ensure:     present
  dmadmin:
    ensure:     present
  oinstall:
    ensure:     present

# UNIX users
user:
  oracle:
    ensure:     present
    managehome: true
    comment:    Oracle Install user
    shell:      '/bin/bash'
    password:   "$1$uwPiRsox$GEe9mUGEav92rx4ooq6Nf." # vagrant
    gid:        dba
    groups:
                - dba
                - oinstall
  dmadmin:
    ensure:     present
    managehome: true
    comment:    Documentum Content Server Install Owner
    shell:      '/bin/bash'
    password:   "$1$uwPiRsox$GEe9mUGEav92rx4ooq6Nf." # vagrant
    gid:        dmadmin
    groups:
                - dba
                - wheel
    require:
                - Group[dba]
                - Group[wheel]

# UNIX folders and files
file:
  '/u01':
    ensure:     directory
  '/u01/app':
    ensure:     directory
  '/u01/app/documentum':
    ensure:     directory
    owner:      dmadmin
    group:      dmadmin
    mode:       '775'
  '/u01/app/documentum/shared':
    ensure:     directory
    owner:      dmadmin
    group:      dmadmin
    mode:       '775'
  '/u01/app/documentum/shared/config':
    ensure:     directory
    owner:      dmadmin
    group:      dmadmin
    mode:       '775'
  '/u01/app/oracle':
    ensure:     directory
    owner:      oracle
    group:      dba
    mode:       '775'
  '/u01/app/oraInventory':
    ensure:     directory
    owner:      oracle
    group:      dba
    mode:       '775'
  '/u01/app/oracle/product':
    ensure:     directory
    owner:      oracle
    group:      dba
    mode:       '775'
  '/u01/app/oracle/product/12.1':
    ensure:     directory
    owner:      oracle
    group:      dba
    mode:       '775'
  '/u01/app/oracle/product/12.1/client':
    ensure:     directory
    owner:      oracle
    group:      dba
    mode:       '775'
  '/home/dmadmin':
    ensure:     directory
    owner:      dmadmin
    group:      dmadmin
    mode:       '775'
  '/home/dmadmin/sig':
    ensure:     directory
    owner:      dmadmin
    group:      dmadmin
    mode:       '775'
  '/home/dmadmin/sig/cs':
    ensure:     directory
    owner:      dmadmin
    group:      dmadmin
    mode:       '775'
  '/home/dmadmin/sig/csp':
    ensure:     directory
    owner:      dmadmin
    group:      dmadmin
    mode:       '775'
  '/home/dmadmin/sig/docbroker':
    ensure:     directory
    owner:      dmadmin
    group:      dmadmin
    mode:       '775'
  '/home/dmadmin/sig/repository':
    ensure:     directory
    owner:      dmadmin
    group:      dmadmin
    mode:       '775'
  '/home/oracle':
    ensure:     directory
    owner:      oracle
    group:      dba
    mode:       '775'
  '/home/oracle/sig':
    ensure:     directory
    owner:      oracle
    group:      dba
    mode:       '775'
  '/home/oracle/sig/client':
    ensure:     directory
    owner:      oracle
    group:      dba
    mode:       '775'

# UNIX services. /etc/services file
etc_services:
  dm_fcms/tcp:
    ensure:   present
    port:     '60000'
    comment:  EMC Documentum Repository - fcms
  dm_fcms/udp:
    ensure:   present
    port:     '60000'
    comment:  EMC Documentum Repository - fcms
  dm_fcms_s/tcp:
    ensure:   present
    port:     '60001'
    comment:  EMC Documentum Repository - fcms
  dm_fcms_s/udp:
    ensure:   present
    port:     '60001'
    comment:  EMC Documentum Repository - fcms
