---

# Puppet Classes to load and execute
classes:
  - etc_services::hiera
  - documentum

# UNIX groups
group:
  dba:
    ensure:     present
  dmadmin:
    ensure:     present

# UNIX users
user:
  dmadmin:
    ensure:     present
    managehome: true
    comment:    Documentum Content Server Install Owner
    shell:      '/bin/bash'
    password:   "$1$uwPiRsox$GEe9mUGEav92rx4ooq6Nf." # vagrant
    gid:        dmadmin
    groups:
                - dba
                - wheel
    require:
                - Group[dba]
                - Group[wheel]

documentum::contentserver::repository:
  ensure:                'file'
  documentum:            '/u01/app/documentum'
  version:               '7.3'
  installer:             '/u01/app/documentum/product/7.3/install'
  docbroker_port:        '1489'
  docbroker_name:        'Docbroker'
  repository_name:       'FCMS'
  repository_id:         '20170110'
  repository_service:    'dm_fcms'
  repository_desc:       'auto repo build'
  bof_registry_password: '1234qwer'
  db_user:               'fcms_repo'
  db_password:           'fcms_repo'
  db_connection:         'orcl'
  db_indexspace:         'fcms_repo'

# UNIX folders and files
file:
  '/u01':
    ensure:     directory
  '/u01/app':
    ensure:     directory
  '/u01/app/documentum':
    ensure:     directory
    owner:      dmadmin
    group:      dmadmin
    mode:       '775'
  '/u01/app/documentum/shared':
    ensure:     directory
    owner:      dmadmin
    group:      dmadmin
    mode:       '775'
  '/u01/app/documentum/shared/config':
    ensure:     directory
    owner:      dmadmin
    group:      dmadmin
    mode:       '775'
  '/home/dmadmin':
    ensure:     directory
    owner:      dmadmin
    group:      dmadmin
    mode:       '775'
  '/home/dmadmin/sig':
    ensure:     directory
    owner:      dmadmin
    group:      dmadmin
    mode:       '775'
  '/home/dmadmin/sig/cs':
    ensure:     directory
    owner:      dmadmin
    group:      dmadmin
    mode:       '775'
  '/home/dmadmin/sig/csp':
    ensure:     directory
    owner:      dmadmin
    group:      dmadmin
    mode:       '775'
  '/home/dmadmin/sig/docbroker':
    ensure:     directory
    owner:      dmadmin
    group:      dmadmin
    mode:       '775'
  '/home/dmadmin/sig/repository':
    ensure:     directory
    owner:      dmadmin
    group:      dmadmin
    mode:       '775'

# UNIX services. /etc/services file
etc_services:
  dm_fcms/tcp:
    ensure:   present
    port:     '60000'
    comment:  EMC Documentum Repository - fcms
  dm_fcms/udp:
    ensure:   present
    port:     '60000'
    comment:  EMC Documentum Repository - fcms
  dm_fcms_s/tcp:
    ensure:   present
    port:     '60001'
    comment:  EMC Documentum Repository - fcms
  dm_fcms_s/udp:
    ensure:   present
    port:     '60001'
    comment:  EMC Documentum Repository - fcms
