---

# Puppet Classes to load and execute
classes:
  - etc_services::hiera
  - documentum

# UNIX groups
group:
  dba:
    ensure:     present
  dmadmin:
    ensure:     present

# UNIX users
user:
  dmadmin:
    ensure:     present
    managehome: true
    comment:    Documentum Content Server Install Owner
    shell:      '/bin/bash'
    password:   "$1$uwPiRsox$GEe9mUGEav92rx4ooq6Nf." # vagrant
    gid:        dmadmin
    groups:
                - dba
                - wheel
    require:
                - Group[dba]
                - Group[wheel]

# UNIX folders and files
file:
  '/u01':
    ensure:     directory
  '/u01/app':
    ensure:     directory
  '/u01/app/documentum':
    ensure:     directory
    owner:      dmadmin
    group:      dmadmin
    mode:       '775'
  '/u01/app/documentum/shared':
    ensure:     directory
    owner:      dmadmin
    group:      dmadmin
    mode:       '775'
  '/u01/app/documentum/shared/config':
    ensure:     directory
    owner:      dmadmin
    group:      dmadmin
    mode:       '775'
  '/home/dmadmin':
    ensure:     directory
    owner:      dmadmin
    group:      dmadmin
    mode:       '775'
  '/home/dmadmin/sig':
    ensure:     directory
    owner:      dmadmin
    group:      dmadmin
    mode:       '775'
  '/home/dmadmin/sig/cs':
    ensure:     directory
    owner:      dmadmin
    group:      dmadmin
    mode:       '775'
  '/home/dmadmin/sig/csp':
    ensure:     directory
    owner:      dmadmin
    group:      dmadmin
    mode:       '775'
  '/home/dmadmin/sig/docbroker':
    ensure:     directory
    owner:      dmadmin
    group:      dmadmin
    mode:       '775'
  '/home/dmadmin/sig/repository':
    ensure:     directory
    owner:      dmadmin
    group:      dmadmin
    mode:       '775'

# UNIX services. /etc/services file
etc_services:
  farrengold/tcp:
    ensure:   present
    port:     '60000'
    comment:  EMC Documentum Repository - farrengold
  farrengold/udp:
    ensure:   present
    port:     '60000'
    comment:  EMC Documentum Repository - farrengold
  farrengold_s/tcp:
    ensure:   present
    port:     '60001'
    comment:  EMC Documentum Repository - farrengold
  farrengold_s/udp:
    ensure:   present
    port:     '60001'
    comment:  EMC Documentum Repository - farrengold
